### ISSUE TITLE
a mistake in getting an element from index.html

### ISSUE THREAD

**Issue by Jamalat-shamallakh** [GSG-G7/AMAI-TODO-List#68]
https://github.com/GSG-G7/AMAI-TODO-List/blob/e4a59a1b3557d1936017266d8de1529be7bde12c/JS/dom.js#L104 
when you add a new element you have an error which is 
```
dom.js:107 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLFormElement.<anonymous> (dom.js:107)
```
because you have a mistake when you get the element, you writ this line 
```
 var sortFormBtn = document.getElementById('add-todo input[type=button]');
``` 
but when you back to index.html there isn`t this id for sort button and getElemetBy
Id can't use as you used, so add an id for the button and use getElemetById in the right way your error will be solved.

**Comment by MohammadAlhalaq** [comment]
resolved
