### ISSUE TITLE
To avoid empty input value

### ISSUE THREAD

**Issue by Jamalat-shamallakh** [GSG-G7/AMAI-TODO-List#71]
https://github.com/GSG-G7/AMAI-TODO-List/blob/e4a59a1b3557d1936017266d8de1529be7bde12c/JS/dom.js#L93 

if I click on submit with empty input or add space without any character it will add, so you can use this or try to solve it as you like
``` 
  if(inputText.value.trim()){

```
it will remove space from the start of a string and check if there a real value

**Comment by MohammadAlhalaq** [comment]
done
